// Auto-generated by: pnpm db:types
// Run `pnpm db:types` after schema changes to regenerate.
// This is a placeholder — replace with generated output once Supabase project is linked.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          subscription_tier: 'free' | 'basic' | 'pro'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['tenants']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['tenants']['Insert']>
      }
      profiles: {
        Row: {
          id: string
          tenant_id: string
          role: 'owner' | 'cashier'
          name_km: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      products: {
        Row: {
          id: string
          tenant_id: string
          name_km: string
          barcode: string | null
          unit: string
          cost_price: number
          sell_price: number
          stock_qty: number
          low_stock_threshold: number
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['products']['Insert']>
      }
      customers: {
        Row: {
          id: string
          tenant_id: string
          name_km: string
          phone: string | null
          debt_balance: number
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['customers']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['customers']['Insert']>
      }
      sales: {
        Row: {
          id: string
          tenant_id: string
          cashier_id: string
          total_amount: number
          paid_amount: number
          payment_type: 'cash' | 'debt' | 'partial'
          customer_id: string | null
          note: string | null
          is_void: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['sales']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['sales']['Insert']>
      }
      sale_items: {
        Row: {
          id: string
          sale_id: string
          tenant_id: string
          product_id: string
          name_km: string
          qty: number
          unit_price: number
          subtotal: number
        }
        Insert: Database['public']['Tables']['sale_items']['Row']
        Update: Partial<Database['public']['Tables']['sale_items']['Insert']>
      }
      debt_transactions: {
        Row: {
          id: string
          tenant_id: string
          customer_id: string
          sale_id: string | null
          amount: number
          type: 'charge' | 'payment'
          note: string | null
          is_void: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['debt_transactions']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['debt_transactions']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
